/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OR1_DEA;

import Muficterials.Panels2;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author computer market
 */
public class DEA_GUI extends javax.swing.JFrame {

    private int number1;
    private int number2;
    private int number3;
    JScrollPane scrollPane;
    DefaultTableModel model;
    JTable table;
    List<String> numdata;
 DEA dea ;
    /**
     * Creates new form DEA_GUI
     */
    public DEA_GUI() {
        initComponents();
        
       ImageIcon icon = new ImageIcon(getClass().getResource("/Images/ImageIcon.png"));
this.setIconImage(icon.getImage());
        
                dea = new DEA();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        First = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Second = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Data Envelopment Analysis");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        Parent.setLayout(new java.awt.CardLayout());

        First.setBackground(new java.awt.Color(0, 51, 51));
        First.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 133, 201));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEA");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Enter the number of objects");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Enter the number of outputs");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Enter the number of inputs");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(28, 133, 201));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );

        javax.swing.GroupLayout FirstLayout = new javax.swing.GroupLayout(First);
        First.setLayout(FirstLayout);
        FirstLayout.setHorizontalGroup(
            FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(FirstLayout.createSequentialGroup()
                .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FirstLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(204, 204, 204)
                        .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(jTextField1))))
                    .addGroup(FirstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        FirstLayout.setVerticalGroup(
            FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Parent.add(First, "card4");

        Second.setBackground(new java.awt.Color(102, 51, 0));
        Second.setLayout(new java.awt.BorderLayout());

        jButton3.setBackground(new java.awt.Color(28, 133, 201));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Solve");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        Second.add(jButton3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(70, 0, 152));

        jPanel3.setBackground(new java.awt.Color(102, 51, 0));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Undo_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Fill the table please...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel7)))
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26))
        );

        Second.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        Parent.add(Second, "card3");

        getContentPane().add(Parent, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int num1 =0 ;
         int num2 = 0 ;
         int num3 = 0 ;
        try{
         num1 = Integer.parseInt(jTextField1.getText());

         num2 = Integer.parseInt(jTextField2.getText());
         num3 = Integer.parseInt(jTextField3.getText());
         
                 this.number1 = num1;
        this.number2 = num2;

        this.number3 = num3;
       

        Parent.removeAll();
        Parent.add(Second);
        Parent.repaint();
        Parent.validate();
        dea.DEAalgo(num1, num2, num3);

        model = new DefaultTableModel(dea.inoutputs, num1);
        table = new JTable(model);
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            for (int i = 0; i < num2+num3; i++) {
table.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            }
             cellRenderer.setHorizontalAlignment(JLabel.CENTER);

        table.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        table.setAutoscrolls(true);
        table.setGridColor(Color.black);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.setBounds(50, 50, 200, 300);
 table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
int index = 0;
                while (index < (number2+number3)) {
                    TableColumn a = table.getColumnModel().getColumn(index);
                    a.setPreferredWidth(150);
                    index++;
                }
                
        scrollPane = new JScrollPane(table, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        getContentPane().add(scrollPane);

        Second.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setVisible(true);
        Second.validate();
        
 if (table.isEditing())
    table.getCellEditor().stopCellEditing();
}catch(Exception e){
        
                            JOptionPane.showMessageDialog(null,"Please ?! Enter numbers in the TextFields");

        
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        TableModel tm = table.getModel();
        double [] coldataofin = new double[number1];
        double [] coldataofout = new double[number1];
                double [][] Points = new double[number1][number2*number3];
String [] effpoints = new String[number1] ;

DecimalFormat numberFormat = new DecimalFormat("#.0000");

        int startofout = number3;
        int s = 0 ;
        
        try{
            
        for(int j=0 ; j<number2;j++){
            
                for (int k = 0; k < number1; k++) {
                    
//                    System.out.println(startofout);
                    coldataofout [k]=Double.parseDouble(table.getModel().getValueAt(k, startofout).toString());

                }
                            
            
        for (int i = 0 ; i <number3; i++) {
            for (int k = 0; k < number1; k++) {
                  coldataofin[k]= Double.parseDouble(table.getModel().getValueAt(k,i).toString());
            }
             dea.algo(coldataofout, coldataofin , s);
             s++ ;
        }
       
        
            for (int i = 0; i < number1; i++) {

                System.out.println(coldataofin[i]+" - "+coldataofout[i]);                
            }
            
                       startofout++;

        }
        
       Points = dea.Points() ;

       for (int i = 0; i < number2*number3; i++) {
            for (int j = 0; j < number1; j++) {

              effpoints[j] = numberFormat.format(Points[j][i]);
            }
           
                    
                
            model.addColumn("Efficiency "+(i+1) , effpoints);
            
             
                        table.setModel(model);

           
        }
       
       int index = 0;
                while (index < (number2+number3)+(number2*number3)) {
                    TableColumn a = table.getColumnModel().getColumn(index);
                    a.setPreferredWidth(150);
                    index++;
                }
       
//       DMU_Chart dmu = new DMU_Chart(Points);
//       dmu.setSize(800,800);
//       dmu.setVisible(true);
}catch(Exception e){
        
                    JOptionPane.showMessageDialog(null,"Please ?! Enter numbers in this Table");

        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        Panels2 elwagha = new Panels2();
               elwagha.setLocationRelativeTo(null);
               elwagha.setVisible(true);
               
               elwagha.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        if (JOptionPane.showConfirmDialog(elwagha, 
            "Are you sure to close this window?", "Really Closing?", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
});
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
                jPanel1.setBackground(new Color(28,133,201));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
              jPanel3.setBackground(new Color(102,34,28));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(102,51,0));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
                this.setVisible(false);
                DEA_GUI dea = new DEA_GUI();
               dea.setLocationRelativeTo(null);
               dea.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
                 if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                 
                     int num1 =0 ;
         int num2 = 0 ;
         int num3 = 0 ;
        try{
         num1 = Integer.parseInt(jTextField1.getText());

         num2 = Integer.parseInt(jTextField2.getText());
         num3 = Integer.parseInt(jTextField3.getText());
         
                 this.number1 = num1;
        this.number2 = num2;

        this.number3 = num3;
       

        Parent.removeAll();
        Parent.add(Second);
        Parent.repaint();
        Parent.validate();
        dea.DEAalgo(num1, num2, num3);

        model = new DefaultTableModel(dea.inoutputs, num1);
        table = new JTable(model);
         DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            for (int i = 0; i < num2+num3; i++) {
table.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            }
             cellRenderer.setHorizontalAlignment(JLabel.CENTER);
             
        table.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        table.setAutoscrolls(true);
        table.setGridColor(Color.black);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.setBounds(50, 50, 200, 300);
 table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
int index = 0;
                while (index < (number2+number3)) {
                    TableColumn a = table.getColumnModel().getColumn(index);
                    a.setPreferredWidth(150);
                    index++;
                }
                
        scrollPane = new JScrollPane(table, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        getContentPane().add(scrollPane);

        Second.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setVisible(true);
        Second.validate();
        
 if (table.isEditing())
    table.getCellEditor().stopCellEditing();
}catch(Exception e){
        
                            JOptionPane.showMessageDialog(null,"Please ?! Enter numbers in the TextFields");

        
        }
        
                 }

    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                 
                     int num1 =0 ;
         int num2 = 0 ;
         int num3 = 0 ;
        try{
         num1 = Integer.parseInt(jTextField1.getText());

         num2 = Integer.parseInt(jTextField2.getText());
         num3 = Integer.parseInt(jTextField3.getText());
         
                 this.number1 = num1;
        this.number2 = num2;

        this.number3 = num3;
       

        Parent.removeAll();
        Parent.add(Second);
        Parent.repaint();
        Parent.validate();
        dea.DEAalgo(num1, num2, num3);

        model = new DefaultTableModel(dea.inoutputs, num1);
        table = new JTable(model);
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            for (int i = 0; i < num2+num3; i++) {
table.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            }
             cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        table.setAutoscrolls(true);
        table.setGridColor(Color.black);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.setBounds(50, 50, 200, 300);
 table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
int index = 0;
                while (index < (number2+number3)) {
                    TableColumn a = table.getColumnModel().getColumn(index);
                    a.setPreferredWidth(150);
                    index++;
                }
                
        scrollPane = new JScrollPane(table, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        getContentPane().add(scrollPane);

        Second.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setVisible(true);
        Second.validate();
        
 if (table.isEditing())
    table.getCellEditor().stopCellEditing();
}catch(Exception e){
        
                            JOptionPane.showMessageDialog(null,"Please ?! Enter numbers in the TextFields");

        
        }
        
                 }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        
                     if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                         
                          double [] coldataofin = new double[number1];
        double [] coldataofout = new double[number1];
                double [][] Points = new double[number1][number2*number3];
String [] effpoints = new String[number1] ;


        int startofout = number3;
        int s = 0 ;
        
        try{
            
        for(int j=0 ; j<number2;j++){
            
                for (int k = 0; k < number1; k++) {
                    
//                    System.out.println(startofout);
                    coldataofout [k]=Double.parseDouble(table.getModel().getValueAt(k, startofout).toString());

                }
                            
            
        for (int i = 0 ; i <number3; i++) {
            for (int k = 0; k < number1; k++) {
                  coldataofin[k]= Double.parseDouble(table.getModel().getValueAt(k,i).toString());
            }
             dea.algo(coldataofout, coldataofin , s);
             s++ ;
        }
       
        
            for (int i = 0; i < number1; i++) {

                System.out.println(coldataofin[i]+" - "+coldataofout[i]);                
            }
            
                       startofout++;

        }
        
       Points = dea.Points() ;

       for (int i = 0; i < number2*number3; i++) {
            for (int j = 0; j < number1; j++) {

              effpoints[j] = Double.toString(Points[j][i]);
            }
           
                    
                
            model.addColumn("Efficiency "+(i+1) , effpoints);
            
             
                        table.setModel(model);

           
        }
       
       
       DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            for (int i = 0; i <(number2+number3)+(number2*number3) ; i++) {
table.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            }
             cellRenderer.setHorizontalAlignment(JLabel.CENTER);
       
             
       int index = 0;
                while (index < (number2+number3)+(number2*number3)) {
                    TableColumn a = table.getColumnModel().getColumn(index);
                    a.setPreferredWidth(150);
                    index++;
                }
       
//       DMU_Chart dmu = new DMU_Chart(Points);
//       dmu.setSize(800,800);
//       dmu.setVisible(true);
}catch(Exception e){
        
                    JOptionPane.showMessageDialog(null,"Please ?! Enter numbers in this Table");

        
        }
        
                     }
                     
    }//GEN-LAST:event_jButton3KeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DEA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DEA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DEA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DEA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DEA_GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel First;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel Second;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
